"""Increase password_hash length

Revision ID: 223118aebbbe
Revises: 8181e7c79bbb
Create Date: 2024-09-08 20:24:20.776484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223118aebbbe'
down_revision = '8181e7c79bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
